### ISSUE TITLE
Maybe wrong reference to some files in setup.py

### ISSUE THREAD

**Issue by leonel-lordford** [videomorph-dev/videomorph#16]
Maikel Llamaret can't use **python setup.py install** and I tried too but there is maybe some misspelled references to files **changelog** and manpage **videomorph.1**, they exists using those names but in **setup.py** references are **changelog.gz** and **videomorph.1.gz** failling while running **python setup.py install** because can't copy source files to destination.

**Comment by lpozo** [comment]
Well, those files are really present, but in the source file (videomorph-1.4.tar.gz) the final names for those files are changelog.gz and videomorph.1.gz so the setup.py must work correctly. This kind of files are released in .gz format, not in plain text as the are in the repo.

**Comment by leonel-lordford** [comment]
I saw the files but they are not compressed as required, we need to fix 
this, maybe we need to add the compressed files to the repo as well... 
just saying...
