### ISSUE TITLE
Not working in Manjaro

### ISSUE THREAD

**Issue by BishopWolf** [videomorph-dev/videomorph#17]
Is there anything else I shall do to make it run in Manjaro??

**Comment by leonel-lordford** [comment]
As far as we know you can use it in Manjaro, we're facing an issue with Manjaro using KDE Plasma, but beside that nothing we know about... what's your problem?
LordFord.

**Comment by BishopWolf** [comment]
Using Manjaro KDE precisely, it just dont start

**Comment by leonel-lordford** [comment]
Hmm... well, seems you need to prepare your environment to run it, check INSTALL and try again, we know there is an issue with systray but still you can run it... Thanks for your feedback...
LordFord.

**Comment by BishopWolf** [comment]
I have found a solution
In setup.py change the lines
       ```
 # Documentation files
        (SYS_PATHS.doc,
         ['README.md', 'LICENSE', 'AUTHORS', 'INSTALL', 'VERSION',
          'copyright','changelog.gz', 'TODO', 'screenshot.png']),
        # User's manual
        (SYS_PATHS.help,
         [VM_PATHS.help + '/manual_es.pdf',
          VM_PATHS.help + '/manual_en.pdf']),
        # Man page
        (SYS_PATHS.man,
         [VM_PATHS.man + '/videomorph.1.gz'])])
```
by the lines 
```
        # Documentation files
        (SYS_PATHS.doc,
         ['README.md', 'LICENSE', 'AUTHORS', 'INSTALL', 'VERSION',
          'copyright','changelog', 'TODO', 'screenshot.png']),
        # User's manual
        (SYS_PATHS.help,
         [VM_PATHS.help + '/manual_es.pdf',
          VM_PATHS.help + '/manual_en.pdf']),
        # Man page
        (SYS_PATHS.man,
         [VM_PATHS.man + '/videomorph.1'])])
```

and it runs smoothly
https://i.imgur.com/IOBvI7P.png

**Comment by stdevOzkar** [comment]
Plz @leonel-lordford @lpozo test the new change, if succeded, make a PR, Use as referral this issue. Thanks a lor @BishopWolf !

**Comment by leonel-lordford** [comment]
Cool... we already fixed that issue, don't know why is not pushed. Either way thanks for your effort, remember we're working on a patch for solving systray issue... If you're facing the same problem and can help with a solution we'll appreciate it a lot.
LordFord.

**Comment by BishopWolf** [comment]
I can't see the systray error in issues

**Comment by BishopWolf** [comment]
There is an extra bug related to this:
If you press changelog the application crashes

I think it searches the compressed version after all

**Comment by BishopWolf** [comment]
OK, reverting the changes described before, compressing the two offender files to tar.gz, renaming them to .gz and installing again
https://i.imgur.com/TC91NOk.png

**Comment by lpozo** [comment]
This is the same issue #16. We already solve this problem on develop branch.
