### ISSUE TITLE
System Tray Icon doesn't work properly on Manjaro/Plasma

### ISSUE THREAD

**Issue by lpozo** [videomorph-dev/videomorph#19]
Reported by Maikel Llamaret. It seems that the app continues running after clicking the main windows close-button. System Tray Icon continues active and the process too.

**Comment by leonel-lordford** [comment]
I'm facing this issue too in Debian/Plasma, I think we can drop this feature for the moment, since there is not mandatory or essential.

**Comment by lpozo** [comment]
We can possibly drop this feature or we can find another way to use notifications without depending on a third party package if possible.

**Comment by lpozo** [comment]
> I'm facing this issue too in Debian/Plasma, I think we can drop this feature for the moment, since there is not mandatory or essential.

Would you like to take care of this problem?

**Comment by leonel-lordford** [comment]
Feature deleted. We will solve this rewriting this feature from scratch using another approach.
