### ISSUE TITLE
App freezes with HD movies on Windows

### ISSUE THREAD

**Issue by lpozo** [videomorph-dev/videomorph#2]
App freezes with certain movies (HD mainly) when reading ffprobe output on Windows platform. converter.media._MediaFile._parse_probe()

**Comment by leonel-lordford** [comment]
Does ffprobe work ok via CLI instead?

**Comment by lpozo** [comment]
Totally. The problem is when `_parse_probe()` method tries to process the file-like object `probe_file` that we get from `platformdeps._Win32Process.spawn_process()`. The for loop just freezes...

**Comment by leonel-lordford** [comment]
We'll try to update the binaries in the Windows Version and let see if this issue is solved.
