### ISSUE TITLE
setting Output Folder

### ISSUE THREAD

**Issue by Axel-Erfurt** [videomorph-dev/videomorph#28]
Selecting the folder will work, but will not take effect until the program is restarted.

After adding a single video file, a blank window remains open (Title: Adding Videos ...)

in videomorph.py I commented out a few lines. Then it works without a window remains open.

`    def _select_files(self, dialog_title, files_filter,
                      source_dir=QDir.homePath(), single_file=False):
        # Validate source_dir
        source_directory = source_dir if isdir(source_dir) else QDir.homePath()

        # Select media files and store their path
        #if single_file:
        #    files_paths, _ = QFileDialog.getOpenFileName(self,
        #                                                 dialog_title,
        #                                                 source_directory,
        #                                                 files_filter)
        #else:
        files_paths, _ = QFileDialog.getOpenFileNames(self,
                                                          dialog_title,
                                                          source_directory,
                                                          files_filter)

        if files_paths:
            # Update the source directory
            if not single_file:
                self.source_dir = dirname(files_paths[0])
        else:
            return None

        return files_paths`

**Comment by lpozo** [comment]
Hi @Axel-Erfurt. Thanks for the head up. We'll check this problem as soon as possible:+1:

**Comment by leonel-lordford** [comment]
Reviewed, we weren't able to reproduce this issue, all our tests run successfully, will close the issue and if needed will be reopened again.
