### ISSUE TITLE
Add new presets for social networks

### ISSUE THREAD

**Issue by lpozo** [videomorph-dev/videomorph#31]
Add new presets for social networks (Youtube, FB, etc.). The intention is to provide our users with presets to convert their videos using the standards of social networks.

**Comment by leonel-lordford** [comment]
This is done! @lpozo will give more details after his commit.

**Comment by lpozo** [comment]
Added presets:

- AVI for YouTube
- MOV for YouTube
- MP4 for YouTube
- MKV H265, for YouTube

**Comment by lpozo** [comment]
These presets are valid for any other social network.
