### ISSUE TITLE
Test and update the current set of presets

### ISSUE THREAD

**Issue by lpozo** [videomorph-dev/videomorph#36]
We need to review/test and update our current set of presets. Remove old ones and add new ones according to market trends.

**Comment by leonel-lordford** [comment]
This is done! @lpozo will give more details after his commit.

**Comment by lpozo** [comment]
We tested and fix all the current presets. Additinaly, several presets from [MystiQ](https://github.com/swl-x/MystiQ) were added and tested as well.

Added presets:

    AVI for YouTube
    DVD PAL
    MOV for YouTube
    MP4 for YouTube
    WMV for the web, Xbox 360, Zune, Power Point
    MKV H265, for YouTube
    MP3 optimized
    OGA and OGA mono
