### ISSUE TITLE
Create an awesome landing page

### ISSUE THREAD

**Issue by lpozo** [videomorph-dev/videomorph#37]
We need a real landing page, maybe using Garv, Jekyll, Pelican or any other static site generator. We can start by using GitHub pages.

**Comment by lpozo** [comment]
Team, we need to brainstorm this issue. I thnik that a static page generated with Pelican or any other tool can solve the problem.

**Comment by leonel-lordford** [comment]
Yes, that can be good enough, the real problem now is that we don't have access (at least that I know) to domain management and the VPS Maikel gave us, so, we need to think on use for now GitHub Pages and update the Project Reame adding this new temporary domain so the page can be accessible at least.

**Comment by lpozo** [comment]
I think GitHub pages is perfect. GitHub pages accepts Jekyll sites. Jekyll has several good themes to choose from.
