### ISSUE TITLE
Problems with Add Customized Profile Option

### ISSUE THREAD

**Issue by llamaret** [videomorph-dev/videomorph#38]
When a user tries to create their own profile, if the profile has errors, the application suddenly closes.
The expected behavior is that the application recognizes whether the format used to complete the profile is valid or not and if it is not valid, or notifies or ignores the profile.
Currently the application is only strict with the field related to the extension. The other three fields can be filled with invalid information. The application does not detect that the information is not valid. It simply closes unexpectedly when trying to save the wrong profile

**Comment by leonel-lordford** [comment]
Feature deleted. We will solve this rewriting this feature from scratch using another approach.
