### ISSUE TITLE
Release version 1.5 with codename: "Canelo"

### ISSUE THREAD

**Issue by lpozo** [videomorph-dev/videomorph#42]
Release version 1.5 with the codename "Canelo" to honor our dear friend Maikel Llamater Heredia.

**Comment by leonel-lordford** [comment]
Completely agree! :-D Let's do it.

**Comment by leonel-lordford** [comment]
Can we define a short list of what we will add for this release? Just to get the job organized.

**Comment by leonel-lordford** [comment]
I think we can try to solve issues #2 #19 #26 #27 #28 #29 #30 (just the icons for now) #31 #35 (let's check this with Osmel) #36 #38 and #41

Also we can add some features from MystiQ to our release in honor to Llamaret!

**Comment by BishopWolf** [comment]
What happened to LLamaret?

**Comment by lpozo** [comment]
@BishopWolf take a look at this: https://gutl.jovenclub.cu/fallece-maikel-llamaret-uno-de-los-impulsores-del-software-libre-en-cuba/

**Comment by leonel-lordford** [comment]
@lpozo and @lordford did a sprint today preparing this 1.5 release to remember our dear friend!

**Comment by leonel-lordford** [comment]
@lpozo I just added a full revision in commit 2f34f16, you only need to review it and update Changelog and we're ready to release 1.5, it's been a month since we lost our friend and it's about time to complete this task. Let me know.

**Comment by lpozo** [comment]
We released this version in memory of our dear friend Maikel Yamaret Heredia. RIP Canelo!
