### ISSUE TITLE
Convert option disabled after stopping previous process

### ISSUE THREAD

**Issue by leonel-lordford** [videomorph-dev/videomorph#7]
After starting a conversion process maybe I wan't to stop, change output dir or make some room in current dir and just re-start conversion again but ***Convert*** action is disabled, just enabled again if I change preset or similar, this also happens after current process finish successfully, actions remains Disabled and maybe I just deleted the current file by mistake and need to reconvert again.

This is in version **1.3.1**

**Comment by lpozo** [comment]
Ok, so we need to enable the conversion option if output directory is changed. I'll review that...

**Comment by leonel-lordford** [comment]
Hmmm... or maybe just enable that option always if there are items in convertion list and no conversion is taking place, of course.

**Comment by lpozo** [comment]
The problem is that it depends on the file status. If all the list is done, you don't have much to do unless you change any conversion option.

**Comment by leonel-lordford** [comment]
Hmmm... well... It seems to, but I just got an email from a friend asking me for get the button enabled **ALWAYS** if there is no task running, he just run out of space and stopped, of course, deleted some extra stuff and still wants to convert using the same output dir but the button is enabled again **ONLY** after changing current directory... we should have the button enabled **always**... but if your patch seems to feel like good UX then we can close this and if needed re-open it again. Thanks for your time.

**Comment by leonel-lordford** [comment]
Done discussing this topic. Closing until needed again. Regards.
